services:
  - type: web
    name: classic-model-business
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/Class_Model_Business-0.0.1-SNAPSHOT.jar
    autoDeploy: true
